Stevenic/storage component
BotBuilderCommunity/botbuilder-community-dotnet pull request #368
Opened 2021-02-28 20:57 UTC by Stevenic

Added new Strorage components and sample app.

2021-03-02 12:24 UTC, garypretty requested changes
Typo in Storage readme title.

@Stevenic do we expect we might add additional items to this package in the future? I am wondering if we should make the name more specific, like "ReadWrite Storage Component" or something, given we will hopefully see a lot of packages created in the future. Not saying we should change this, just a note for discussion.

2021-03-02 12:24 UTC, garypretty commented on libraries/Bot.Builder.Community.Components.Storage/readme.md
> +## CallDialogs Component for Bot Framework Composer
Typo, should be storage.

2021-03-02 12:24 UTC, garypretty commented on samples/components/CallDialogsSample/.gitignore
> +**/appsettings.json
I thought this was already excluded by the repo gitignore - not a problem right now. I have an action to consolidate both gitignore and also StyleCop rules across the Community at some point, so we can leave this for now.

2021-03-06 18:35 UTC, Stevenic commented
> @Stevenic do we expect we might add additional items to this package in the future? I am wondering if we should make the name more specific, like "ReadWrite Storage Component" or something, given we will hopefully see a lot of packages created in the future. Not saying we should change this, just a note for discussion.

It's possible that more components will get added. For example the underlying storage provider allows for batch reads & writes which I'm not currently exposing.

I called this component Storage because the actions are tied directly to working with the bots IStorage provider.

2021-03-06 18:37 UTC, Stevenic commented on samples/components/CallDialogsSample/.gitignore
> +**/appsettings.json
This gets added by composer. I didn't modify anything that composer generates.

2021-03-06 18:58 UTC, Stevenic commented
I removed all of the copyright headers from this branch. Just apply it after the other PR and it should essentially update that sample as well

2021-03-16 16:44 UTC, merged