Add activity to google event for GoogleBusinessMessagingRequestMapper
BotBuilderCommunity/botbuilder-community-dotnet pull request #483
Opened 2022-05-16 07:47 UTC by timenick

- Add google event model
- Add activity to google event support

2022-05-18 08:20 UTC, garypretty requested changes

2022-05-18 08:20 UTC, garypretty commented on libraries/Bot.Builder.Community.Components.Adapters.GoogleBusiness.Core/Model/OutgoingEvent.cs
> +            DisplayName = "Contoso",
Consider using a different name here I think - possibly just "Bot".

2022-05-18 08:33 UTC, timenick commented on libraries/Bot.Builder.Community.Components.Adapters.GoogleBusiness.Core/Model/OutgoingEvent.cs
> +            DisplayName = "Contoso",
Shall we also change the DisplayName in OutgoingMessage?

2022-05-24 08:22 UTC, garypretty approved these changes

2022-05-24 08:22 UTC, merged